// Code generated by go-swagger; DO NOT EDIT.

package contact_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewContcatCommentUpdateParams creates a new ContcatCommentUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContcatCommentUpdateParams() *ContcatCommentUpdateParams {
	return &ContcatCommentUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContcatCommentUpdateParamsWithTimeout creates a new ContcatCommentUpdateParams object
// with the ability to set a timeout on a request.
func NewContcatCommentUpdateParamsWithTimeout(timeout time.Duration) *ContcatCommentUpdateParams {
	return &ContcatCommentUpdateParams{
		timeout: timeout,
	}
}

// NewContcatCommentUpdateParamsWithContext creates a new ContcatCommentUpdateParams object
// with the ability to set a context for a request.
func NewContcatCommentUpdateParamsWithContext(ctx context.Context) *ContcatCommentUpdateParams {
	return &ContcatCommentUpdateParams{
		Context: ctx,
	}
}

// NewContcatCommentUpdateParamsWithHTTPClient creates a new ContcatCommentUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewContcatCommentUpdateParamsWithHTTPClient(client *http.Client) *ContcatCommentUpdateParams {
	return &ContcatCommentUpdateParams{
		HTTPClient: client,
	}
}

/*
ContcatCommentUpdateParams contains all the parameters to send to the API endpoint

	for the contcat comment update operation.

	Typically these are written to a http.Request.
*/
type ContcatCommentUpdateParams struct {

	// XDomainrobot2FAToken.
	//
	// Format: int32
	XDomainrobot2FAToken *int32

	// XDomainrobotBulkLimit.
	//
	// Format: int32
	XDomainrobotBulkLimit *int32

	// XDomainrobotContext.
	//
	// Format: int32
	XDomainrobotContext *int32

	// XDomainrobotDemo.
	XDomainrobotDemo *bool

	// XDomainrobotDomainSafePin.
	XDomainrobotDomainSafePin *string

	// XDomainrobotDomainSafeTan.
	XDomainrobotDomainSafeTan *string

	// XDomainrobotDomainSafeTransaction.
	XDomainrobotDomainSafeTransaction *string

	// XDomainrobotDomainSafeTransactionExpire.
	//
	// Format: date-time
	XDomainrobotDomainSafeTransactionExpire *strfmt.DateTime

	// XDomainrobotOwnerContext.
	//
	// Format: int32
	XDomainrobotOwnerContext *int32

	// XDomainrobotOwnerUser.
	XDomainrobotOwnerUser *string

	// XDomainrobotSessionID.
	XDomainrobotSessionID *string

	// XDomainrobotWS.
	XDomainrobotWS *string

	/* Body.

	   contact
	*/
	Body *models.Contact

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contcat comment update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContcatCommentUpdateParams) WithDefaults() *ContcatCommentUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contcat comment update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContcatCommentUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithTimeout(timeout time.Duration) *ContcatCommentUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithContext(ctx context.Context) *ContcatCommentUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithHTTPClient(client *http.Client) *ContcatCommentUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobot2FAToken adds the xDomainrobot2FAToken to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobot2FAToken(xDomainrobot2FAToken *int32) *ContcatCommentUpdateParams {
	o.SetXDomainrobot2FAToken(xDomainrobot2FAToken)
	return o
}

// SetXDomainrobot2FAToken adds the xDomainrobot2FAToken to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobot2FAToken(xDomainrobot2FAToken *int32) {
	o.XDomainrobot2FAToken = xDomainrobot2FAToken
}

// WithXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) *ContcatCommentUpdateParams {
	o.SetXDomainrobotBulkLimit(xDomainrobotBulkLimit)
	return o
}

// SetXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) {
	o.XDomainrobotBulkLimit = xDomainrobotBulkLimit
}

// WithXDomainrobotContext adds the xDomainrobotContext to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotContext(xDomainrobotContext *int32) *ContcatCommentUpdateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotContext(xDomainrobotContext *int32) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotDemo(xDomainrobotDemo *bool) *ContcatCommentUpdateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotDemo(xDomainrobotDemo *bool) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin)
	return o
}

// SetXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) {
	o.XDomainrobotDomainSafePin = xDomainrobotDomainSafePin
}

// WithXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan)
	return o
}

// SetXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) {
	o.XDomainrobotDomainSafeTan = xDomainrobotDomainSafeTan
}

// WithXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction)
	return o
}

// SetXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) {
	o.XDomainrobotDomainSafeTransaction = xDomainrobotDomainSafeTransaction
}

// WithXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) *ContcatCommentUpdateParams {
	o.SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire)
	return o
}

// SetXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) {
	o.XDomainrobotDomainSafeTransactionExpire = xDomainrobotDomainSafeTransactionExpire
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) *ContcatCommentUpdateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithXDomainrobotWS(xDomainrobotWS *string) *ContcatCommentUpdateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithBody(body *models.Contact) *ContcatCommentUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetBody(body *models.Contact) {
	o.Body = body
}

// WithID adds the id to the contcat comment update params
func (o *ContcatCommentUpdateParams) WithID(id int32) *ContcatCommentUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the contcat comment update params
func (o *ContcatCommentUpdateParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ContcatCommentUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobot2FAToken != nil {

		// header param X-Domainrobot-2FA-Token
		if err := r.SetHeaderParam("X-Domainrobot-2FA-Token", swag.FormatInt32(*o.XDomainrobot2FAToken)); err != nil {
			return err
		}
	}

	if o.XDomainrobotBulkLimit != nil {

		// header param X-Domainrobot-Bulk-Limit
		if err := r.SetHeaderParam("X-Domainrobot-Bulk-Limit", swag.FormatInt32(*o.XDomainrobotBulkLimit)); err != nil {
			return err
		}
	}

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", swag.FormatInt32(*o.XDomainrobotContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", swag.FormatBool(*o.XDomainrobotDemo)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafePin != nil {

		// header param X-Domainrobot-Domain-Safe-Pin
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Pin", *o.XDomainrobotDomainSafePin); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTan != nil {

		// header param X-Domainrobot-Domain-Safe-Tan
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Tan", *o.XDomainrobotDomainSafeTan); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransaction != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction", *o.XDomainrobotDomainSafeTransaction); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransactionExpire != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction-Expire
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction-Expire", o.XDomainrobotDomainSafeTransactionExpire.String()); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", swag.FormatInt32(*o.XDomainrobotOwnerContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}
	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}
	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
