// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewDomainCancelationCreateParams creates a new DomainCancelationCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDomainCancelationCreateParams() *DomainCancelationCreateParams {
	return &DomainCancelationCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDomainCancelationCreateParamsWithTimeout creates a new DomainCancelationCreateParams object
// with the ability to set a timeout on a request.
func NewDomainCancelationCreateParamsWithTimeout(timeout time.Duration) *DomainCancelationCreateParams {
	return &DomainCancelationCreateParams{
		timeout: timeout,
	}
}

// NewDomainCancelationCreateParamsWithContext creates a new DomainCancelationCreateParams object
// with the ability to set a context for a request.
func NewDomainCancelationCreateParamsWithContext(ctx context.Context) *DomainCancelationCreateParams {
	return &DomainCancelationCreateParams{
		Context: ctx,
	}
}

// NewDomainCancelationCreateParamsWithHTTPClient creates a new DomainCancelationCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDomainCancelationCreateParamsWithHTTPClient(client *http.Client) *DomainCancelationCreateParams {
	return &DomainCancelationCreateParams{
		HTTPClient: client,
	}
}

/*
DomainCancelationCreateParams contains all the parameters to send to the API endpoint

	for the domain cancelation create operation.

	Typically these are written to a http.Request.
*/
type DomainCancelationCreateParams struct {

	// XDomainrobot2FAToken.
	//
	// Format: int32
	XDomainrobot2FAToken *int32

	// XDomainrobotBulkLimit.
	//
	// Format: int32
	XDomainrobotBulkLimit *int32

	// XDomainrobotContext.
	//
	// Format: int32
	XDomainrobotContext *int32

	// XDomainrobotDemo.
	XDomainrobotDemo *bool

	// XDomainrobotDomainSafePin.
	XDomainrobotDomainSafePin *string

	// XDomainrobotDomainSafeTan.
	XDomainrobotDomainSafeTan *string

	// XDomainrobotDomainSafeTransaction.
	XDomainrobotDomainSafeTransaction *string

	// XDomainrobotDomainSafeTransactionExpire.
	//
	// Format: date-time
	XDomainrobotDomainSafeTransactionExpire *strfmt.DateTime

	// XDomainrobotOwnerContext.
	//
	// Format: int32
	XDomainrobotOwnerContext *int32

	// XDomainrobotOwnerUser.
	XDomainrobotOwnerUser *string

	// XDomainrobotSessionID.
	XDomainrobotSessionID *string

	// XDomainrobotWS.
	XDomainrobotWS *string

	/* Body.

	   domain
	*/
	Body *models.DomainCancelation

	// Name.
	Name string

	/* ReplyTo.

	   The query parameter to override the  default reply to address.
	*/
	ReplyTo *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the domain cancelation create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DomainCancelationCreateParams) WithDefaults() *DomainCancelationCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the domain cancelation create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DomainCancelationCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithTimeout(timeout time.Duration) *DomainCancelationCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithContext(ctx context.Context) *DomainCancelationCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithHTTPClient(client *http.Client) *DomainCancelationCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobot2FAToken adds the xDomainrobot2FAToken to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobot2FAToken(xDomainrobot2FAToken *int32) *DomainCancelationCreateParams {
	o.SetXDomainrobot2FAToken(xDomainrobot2FAToken)
	return o
}

// SetXDomainrobot2FAToken adds the xDomainrobot2FAToken to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobot2FAToken(xDomainrobot2FAToken *int32) {
	o.XDomainrobot2FAToken = xDomainrobot2FAToken
}

// WithXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) *DomainCancelationCreateParams {
	o.SetXDomainrobotBulkLimit(xDomainrobotBulkLimit)
	return o
}

// SetXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) {
	o.XDomainrobotBulkLimit = xDomainrobotBulkLimit
}

// WithXDomainrobotContext adds the xDomainrobotContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotContext(xDomainrobotContext *int32) *DomainCancelationCreateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotContext(xDomainrobotContext *int32) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDemo(xDomainrobotDemo *bool) *DomainCancelationCreateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDemo(xDomainrobotDemo *bool) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin)
	return o
}

// SetXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) {
	o.XDomainrobotDomainSafePin = xDomainrobotDomainSafePin
}

// WithXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan)
	return o
}

// SetXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) {
	o.XDomainrobotDomainSafeTan = xDomainrobotDomainSafeTan
}

// WithXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction)
	return o
}

// SetXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) {
	o.XDomainrobotDomainSafeTransaction = xDomainrobotDomainSafeTransaction
}

// WithXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) *DomainCancelationCreateParams {
	o.SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire)
	return o
}

// SetXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) {
	o.XDomainrobotDomainSafeTransactionExpire = xDomainrobotDomainSafeTransactionExpire
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) *DomainCancelationCreateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithXDomainrobotWS(xDomainrobotWS *string) *DomainCancelationCreateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithBody(body *models.DomainCancelation) *DomainCancelationCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetBody(body *models.DomainCancelation) {
	o.Body = body
}

// WithName adds the name to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithName(name string) *DomainCancelationCreateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetName(name string) {
	o.Name = name
}

// WithReplyTo adds the replyTo to the domain cancelation create params
func (o *DomainCancelationCreateParams) WithReplyTo(replyTo *string) *DomainCancelationCreateParams {
	o.SetReplyTo(replyTo)
	return o
}

// SetReplyTo adds the replyTo to the domain cancelation create params
func (o *DomainCancelationCreateParams) SetReplyTo(replyTo *string) {
	o.ReplyTo = replyTo
}

// WriteToRequest writes these params to a swagger request
func (o *DomainCancelationCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobot2FAToken != nil {

		// header param X-Domainrobot-2FA-Token
		if err := r.SetHeaderParam("X-Domainrobot-2FA-Token", swag.FormatInt32(*o.XDomainrobot2FAToken)); err != nil {
			return err
		}
	}

	if o.XDomainrobotBulkLimit != nil {

		// header param X-Domainrobot-Bulk-Limit
		if err := r.SetHeaderParam("X-Domainrobot-Bulk-Limit", swag.FormatInt32(*o.XDomainrobotBulkLimit)); err != nil {
			return err
		}
	}

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", swag.FormatInt32(*o.XDomainrobotContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", swag.FormatBool(*o.XDomainrobotDemo)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafePin != nil {

		// header param X-Domainrobot-Domain-Safe-Pin
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Pin", *o.XDomainrobotDomainSafePin); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTan != nil {

		// header param X-Domainrobot-Domain-Safe-Tan
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Tan", *o.XDomainrobotDomainSafeTan); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransaction != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction", *o.XDomainrobotDomainSafeTransaction); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransactionExpire != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction-Expire
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction-Expire", o.XDomainrobotDomainSafeTransactionExpire.String()); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", swag.FormatInt32(*o.XDomainrobotOwnerContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}
	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}
	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.ReplyTo != nil {

		// query param replyTo
		var qrReplyTo string

		if o.ReplyTo != nil {
			qrReplyTo = *o.ReplyTo
		}
		qReplyTo := qrReplyTo
		if qReplyTo != "" {

			if err := r.SetQueryParam("replyTo", qReplyTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
