// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// DomainsDeleteDomainSafeReader is a Reader for the DomainsDeleteDomainSafe structure.
type DomainsDeleteDomainSafeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainsDeleteDomainSafeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDomainsDeleteDomainSafeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /bulk/domain/_domainSafe] domainsDeleteDomainSafe", response, response.Code())
	}
}

// NewDomainsDeleteDomainSafeOK creates a DomainsDeleteDomainSafeOK with default headers values
func NewDomainsDeleteDomainSafeOK() *DomainsDeleteDomainSafeOK {
	return &DomainsDeleteDomainSafeOK{}
}

/*
DomainsDeleteDomainSafeOK describes a response with status code 200, with default header values.

successful operation
*/
type DomainsDeleteDomainSafeOK struct {
	Payload *models.JSONResponseDataListJSONResponseDataDomain
}

// IsSuccess returns true when this domains delete domain safe o k response has a 2xx status code
func (o *DomainsDeleteDomainSafeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this domains delete domain safe o k response has a 3xx status code
func (o *DomainsDeleteDomainSafeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this domains delete domain safe o k response has a 4xx status code
func (o *DomainsDeleteDomainSafeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this domains delete domain safe o k response has a 5xx status code
func (o *DomainsDeleteDomainSafeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this domains delete domain safe o k response a status code equal to that given
func (o *DomainsDeleteDomainSafeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the domains delete domain safe o k response
func (o *DomainsDeleteDomainSafeOK) Code() int {
	return 200
}

func (o *DomainsDeleteDomainSafeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /bulk/domain/_domainSafe][%d] domainsDeleteDomainSafeOK %s", 200, payload)
}

func (o *DomainsDeleteDomainSafeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /bulk/domain/_domainSafe][%d] domainsDeleteDomainSafeOK %s", 200, payload)
}

func (o *DomainsDeleteDomainSafeOK) GetPayload() *models.JSONResponseDataListJSONResponseDataDomain {
	return o.Payload
}

func (o *DomainsDeleteDomainSafeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataListJSONResponseDataDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
