// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// DomainAuthinfo1DeleteReader is a Reader for the DomainAuthinfo1Delete structure.
type DomainAuthinfo1DeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainAuthinfo1DeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDomainAuthinfo1DeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDomainAuthinfo1DeleteOK creates a DomainAuthinfo1DeleteOK with default headers values
func NewDomainAuthinfo1DeleteOK() *DomainAuthinfo1DeleteOK {
	return &DomainAuthinfo1DeleteOK{}
}

/*DomainAuthinfo1DeleteOK handles this case with default header values.

successful operation
*/
type DomainAuthinfo1DeleteOK struct {
	Payload *models.JSONResponseDataJSONNoData
}

func (o *DomainAuthinfo1DeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /domain/{name}/_authinfo1][%d] domainAuthinfo1DeleteOK  %+v", 200, o.Payload)
}

func (o *DomainAuthinfo1DeleteOK) GetPayload() *models.JSONResponseDataJSONNoData {
	return o.Payload
}

func (o *DomainAuthinfo1DeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataJSONNoData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
