// Code generated by go-swagger; DO NOT EDIT.

package domain_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// DomainInfoReader is a Reader for the DomainInfo structure.
type DomainInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDomainInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /domain/{name}] domainInfo", response, response.Code())
	}
}

// NewDomainInfoOK creates a DomainInfoOK with default headers values
func NewDomainInfoOK() *DomainInfoOK {
	return &DomainInfoOK{}
}

/*
DomainInfoOK describes a response with status code 200, with default header values.

successful operation
*/
type DomainInfoOK struct {
	Payload *models.JSONResponseDataDomain
}

// IsSuccess returns true when this domain info o k response has a 2xx status code
func (o *DomainInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this domain info o k response has a 3xx status code
func (o *DomainInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this domain info o k response has a 4xx status code
func (o *DomainInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this domain info o k response has a 5xx status code
func (o *DomainInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this domain info o k response a status code equal to that given
func (o *DomainInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the domain info o k response
func (o *DomainInfoOK) Code() int {
	return 200
}

func (o *DomainInfoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /domain/{name}][%d] domainInfoOK %s", 200, payload)
}

func (o *DomainInfoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /domain/{name}][%d] domainInfoOK %s", 200, payload)
}

func (o *DomainInfoOK) GetPayload() *models.JSONResponseDataDomain {
	return o.Payload
}

func (o *DomainInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataDomain)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
