// Code generated by go-swagger; DO NOT EDIT.

package customer_price_list_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewCustomerPriceListDeletesParams creates a new CustomerPriceListDeletesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerPriceListDeletesParams() *CustomerPriceListDeletesParams {
	return &CustomerPriceListDeletesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerPriceListDeletesParamsWithTimeout creates a new CustomerPriceListDeletesParams object
// with the ability to set a timeout on a request.
func NewCustomerPriceListDeletesParamsWithTimeout(timeout time.Duration) *CustomerPriceListDeletesParams {
	return &CustomerPriceListDeletesParams{
		timeout: timeout,
	}
}

// NewCustomerPriceListDeletesParamsWithContext creates a new CustomerPriceListDeletesParams object
// with the ability to set a context for a request.
func NewCustomerPriceListDeletesParamsWithContext(ctx context.Context) *CustomerPriceListDeletesParams {
	return &CustomerPriceListDeletesParams{
		Context: ctx,
	}
}

// NewCustomerPriceListDeletesParamsWithHTTPClient creates a new CustomerPriceListDeletesParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerPriceListDeletesParamsWithHTTPClient(client *http.Client) *CustomerPriceListDeletesParams {
	return &CustomerPriceListDeletesParams{
		HTTPClient: client,
	}
}

/*
CustomerPriceListDeletesParams contains all the parameters to send to the API endpoint

	for the customer price list deletes operation.

	Typically these are written to a http.Request.
*/
type CustomerPriceListDeletesParams struct {

	// XDomainrobot2FAToken.
	//
	// Format: int32
	XDomainrobot2FAToken *int32

	// XDomainrobotBulkLimit.
	//
	// Format: int32
	XDomainrobotBulkLimit *int32

	// XDomainrobotContext.
	//
	// Format: int32
	XDomainrobotContext *int32

	// XDomainrobotDemo.
	XDomainrobotDemo *bool

	// XDomainrobotDomainSafePin.
	XDomainrobotDomainSafePin *string

	// XDomainrobotDomainSafeTan.
	XDomainrobotDomainSafeTan *string

	// XDomainrobotDomainSafeTransaction.
	XDomainrobotDomainSafeTransaction *string

	// XDomainrobotDomainSafeTransactionExpire.
	//
	// Format: date-time
	XDomainrobotDomainSafeTransactionExpire *strfmt.DateTime

	// XDomainrobotOwnerContext.
	//
	// Format: int32
	XDomainrobotOwnerContext *int32

	// XDomainrobotOwnerUser.
	XDomainrobotOwnerUser *string

	// XDomainrobotSessionID.
	XDomainrobotSessionID *string

	// XDomainrobotWS.
	XDomainrobotWS *string

	/* Body.

	   customerPriceLists
	*/
	Body *models.BulkCustomerPriceListDeleteRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer price list deletes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPriceListDeletesParams) WithDefaults() *CustomerPriceListDeletesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer price list deletes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerPriceListDeletesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithTimeout(timeout time.Duration) *CustomerPriceListDeletesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithContext(ctx context.Context) *CustomerPriceListDeletesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithHTTPClient(client *http.Client) *CustomerPriceListDeletesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobot2FAToken adds the xDomainrobot2FAToken to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobot2FAToken(xDomainrobot2FAToken *int32) *CustomerPriceListDeletesParams {
	o.SetXDomainrobot2FAToken(xDomainrobot2FAToken)
	return o
}

// SetXDomainrobot2FAToken adds the xDomainrobot2FAToken to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobot2FAToken(xDomainrobot2FAToken *int32) {
	o.XDomainrobot2FAToken = xDomainrobot2FAToken
}

// WithXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotBulkLimit(xDomainrobotBulkLimit)
	return o
}

// SetXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) {
	o.XDomainrobotBulkLimit = xDomainrobotBulkLimit
}

// WithXDomainrobotContext adds the xDomainrobotContext to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotContext(xDomainrobotContext *int32) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotContext(xDomainrobotContext *int32) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotDemo(xDomainrobotDemo *bool) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotDemo(xDomainrobotDemo *bool) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin)
	return o
}

// SetXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) {
	o.XDomainrobotDomainSafePin = xDomainrobotDomainSafePin
}

// WithXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan)
	return o
}

// SetXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) {
	o.XDomainrobotDomainSafeTan = xDomainrobotDomainSafeTan
}

// WithXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction)
	return o
}

// SetXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) {
	o.XDomainrobotDomainSafeTransaction = xDomainrobotDomainSafeTransaction
}

// WithXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire)
	return o
}

// SetXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) {
	o.XDomainrobotDomainSafeTransactionExpire = xDomainrobotDomainSafeTransactionExpire
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithXDomainrobotWS(xDomainrobotWS *string) *CustomerPriceListDeletesParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) WithBody(body *models.BulkCustomerPriceListDeleteRequest) *CustomerPriceListDeletesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer price list deletes params
func (o *CustomerPriceListDeletesParams) SetBody(body *models.BulkCustomerPriceListDeleteRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerPriceListDeletesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobot2FAToken != nil {

		// header param X-Domainrobot-2FA-Token
		if err := r.SetHeaderParam("X-Domainrobot-2FA-Token", swag.FormatInt32(*o.XDomainrobot2FAToken)); err != nil {
			return err
		}
	}

	if o.XDomainrobotBulkLimit != nil {

		// header param X-Domainrobot-Bulk-Limit
		if err := r.SetHeaderParam("X-Domainrobot-Bulk-Limit", swag.FormatInt32(*o.XDomainrobotBulkLimit)); err != nil {
			return err
		}
	}

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", swag.FormatInt32(*o.XDomainrobotContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", swag.FormatBool(*o.XDomainrobotDemo)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafePin != nil {

		// header param X-Domainrobot-Domain-Safe-Pin
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Pin", *o.XDomainrobotDomainSafePin); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTan != nil {

		// header param X-Domainrobot-Domain-Safe-Tan
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Tan", *o.XDomainrobotDomainSafeTan); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransaction != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction", *o.XDomainrobotDomainSafeTransaction); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransactionExpire != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction-Expire
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction-Expire", o.XDomainrobotDomainSafeTransactionExpire.String()); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", swag.FormatInt32(*o.XDomainrobotOwnerContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}
	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}
	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
