// Code generated by go-swagger; DO NOT EDIT.

package accounting_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewAccountingDocumentCalculateParams creates a new AccountingDocumentCalculateParams object
// with the default values initialized.
func NewAccountingDocumentCalculateParams() *AccountingDocumentCalculateParams {
	var ()
	return &AccountingDocumentCalculateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAccountingDocumentCalculateParamsWithTimeout creates a new AccountingDocumentCalculateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAccountingDocumentCalculateParamsWithTimeout(timeout time.Duration) *AccountingDocumentCalculateParams {
	var ()
	return &AccountingDocumentCalculateParams{

		timeout: timeout,
	}
}

// NewAccountingDocumentCalculateParamsWithContext creates a new AccountingDocumentCalculateParams object
// with the default values initialized, and the ability to set a context for a request
func NewAccountingDocumentCalculateParamsWithContext(ctx context.Context) *AccountingDocumentCalculateParams {
	var ()
	return &AccountingDocumentCalculateParams{

		Context: ctx,
	}
}

// NewAccountingDocumentCalculateParamsWithHTTPClient creates a new AccountingDocumentCalculateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAccountingDocumentCalculateParamsWithHTTPClient(client *http.Client) *AccountingDocumentCalculateParams {
	var ()
	return &AccountingDocumentCalculateParams{
		HTTPClient: client,
	}
}

/*AccountingDocumentCalculateParams contains all the parameters to send to the API endpoint
for the accounting document calculate operation typically these are written to a http.Request
*/
type AccountingDocumentCalculateParams struct {

	/*XDomainrobotBulkLimit*/
	XDomainrobotBulkLimit *int32
	/*XDomainrobotContext*/
	XDomainrobotContext *int32
	/*XDomainrobotDemo*/
	XDomainrobotDemo *bool
	/*XDomainrobotDomainSafePin*/
	XDomainrobotDomainSafePin *string
	/*XDomainrobotDomainSafeTan*/
	XDomainrobotDomainSafeTan *string
	/*XDomainrobotDomainSafeTransaction*/
	XDomainrobotDomainSafeTransaction *string
	/*XDomainrobotDomainSafeTransactionExpire*/
	XDomainrobotDomainSafeTransactionExpire *strfmt.DateTime
	/*XDomainrobotOwnerContext*/
	XDomainrobotOwnerContext *int32
	/*XDomainrobotOwnerUser*/
	XDomainrobotOwnerUser *string
	/*XDomainrobotSessionID*/
	XDomainrobotSessionID *string
	/*XDomainrobotWS*/
	XDomainrobotWS *string
	/*Body
	  accountingDocument

	*/
	Body *models.AccountingDocument

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithTimeout(timeout time.Duration) *AccountingDocumentCalculateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithContext(ctx context.Context) *AccountingDocumentCalculateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithHTTPClient(client *http.Client) *AccountingDocumentCalculateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotBulkLimit(xDomainrobotBulkLimit)
	return o
}

// SetXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) {
	o.XDomainrobotBulkLimit = xDomainrobotBulkLimit
}

// WithXDomainrobotContext adds the xDomainrobotContext to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotContext(xDomainrobotContext *int32) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotContext(xDomainrobotContext *int32) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotDemo(xDomainrobotDemo *bool) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotDemo(xDomainrobotDemo *bool) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin)
	return o
}

// SetXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) {
	o.XDomainrobotDomainSafePin = xDomainrobotDomainSafePin
}

// WithXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan)
	return o
}

// SetXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) {
	o.XDomainrobotDomainSafeTan = xDomainrobotDomainSafeTan
}

// WithXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction)
	return o
}

// SetXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) {
	o.XDomainrobotDomainSafeTransaction = xDomainrobotDomainSafeTransaction
}

// WithXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire)
	return o
}

// SetXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) {
	o.XDomainrobotDomainSafeTransactionExpire = xDomainrobotDomainSafeTransactionExpire
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithXDomainrobotWS(xDomainrobotWS *string) *AccountingDocumentCalculateParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) WithBody(body *models.AccountingDocument) *AccountingDocumentCalculateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the accounting document calculate params
func (o *AccountingDocumentCalculateParams) SetBody(body *models.AccountingDocument) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AccountingDocumentCalculateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobotBulkLimit != nil {

		// header param X-Domainrobot-Bulk-Limit
		if err := r.SetHeaderParam("X-Domainrobot-Bulk-Limit", swag.FormatInt32(*o.XDomainrobotBulkLimit)); err != nil {
			return err
		}

	}

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", swag.FormatInt32(*o.XDomainrobotContext)); err != nil {
			return err
		}

	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", swag.FormatBool(*o.XDomainrobotDemo)); err != nil {
			return err
		}

	}

	if o.XDomainrobotDomainSafePin != nil {

		// header param X-Domainrobot-Domain-Safe-Pin
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Pin", *o.XDomainrobotDomainSafePin); err != nil {
			return err
		}

	}

	if o.XDomainrobotDomainSafeTan != nil {

		// header param X-Domainrobot-Domain-Safe-Tan
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Tan", *o.XDomainrobotDomainSafeTan); err != nil {
			return err
		}

	}

	if o.XDomainrobotDomainSafeTransaction != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction", *o.XDomainrobotDomainSafeTransaction); err != nil {
			return err
		}

	}

	if o.XDomainrobotDomainSafeTransactionExpire != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction-Expire
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction-Expire", o.XDomainrobotDomainSafeTransactionExpire.String()); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", swag.FormatInt32(*o.XDomainrobotOwnerContext)); err != nil {
			return err
		}

	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}

	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}

	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
