// Code generated by go-swagger; DO NOT EDIT.

package contact_document_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// DocumentCopyReader is a Reader for the DocumentCopy structure.
type DocumentCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DocumentCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDocumentCopyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /contact/{id}/document/{type}/_copy] documentCopy", response, response.Code())
	}
}

// NewDocumentCopyOK creates a DocumentCopyOK with default headers values
func NewDocumentCopyOK() *DocumentCopyOK {
	return &DocumentCopyOK{}
}

/*
DocumentCopyOK describes a response with status code 200, with default header values.

successful operation
*/
type DocumentCopyOK struct {
	Payload *models.JSONResponseDataContactDocument
}

// IsSuccess returns true when this document copy o k response has a 2xx status code
func (o *DocumentCopyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this document copy o k response has a 3xx status code
func (o *DocumentCopyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this document copy o k response has a 4xx status code
func (o *DocumentCopyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this document copy o k response has a 5xx status code
func (o *DocumentCopyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this document copy o k response a status code equal to that given
func (o *DocumentCopyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the document copy o k response
func (o *DocumentCopyOK) Code() int {
	return 200
}

func (o *DocumentCopyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /contact/{id}/document/{type}/_copy][%d] documentCopyOK %s", 200, payload)
}

func (o *DocumentCopyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /contact/{id}/document/{type}/_copy][%d] documentCopyOK %s", 200, payload)
}

func (o *DocumentCopyOK) GetPayload() *models.JSONResponseDataContactDocument {
	return o.Payload
}

func (o *DocumentCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataContactDocument)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
