// Code generated by go-swagger; DO NOT EDIT.

package user_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// UserProfileInfoReader is a Reader for the UserProfileInfo structure.
type UserProfileInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserProfileInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserProfileInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserProfileInfoOK creates a UserProfileInfoOK with default headers values
func NewUserProfileInfoOK() *UserProfileInfoOK {
	return &UserProfileInfoOK{}
}

/*UserProfileInfoOK handles this case with default header values.

successful operation
*/
type UserProfileInfoOK struct {
	Payload *models.JSONResponseDataUserProfileViews
}

func (o *UserProfileInfoOK) Error() string {
	return fmt.Sprintf("[GET /user/{name}/{context}/profile][%d] userProfileInfoOK  %+v", 200, o.Payload)
}

func (o *UserProfileInfoOK) GetPayload() *models.JSONResponseDataUserProfileViews {
	return o.Payload
}

func (o *UserProfileInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataUserProfileViews)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
