// Code generated by go-swagger; DO NOT EDIT.

package user_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// UserBillingLimitInfoReader is a Reader for the UserBillingLimitInfo structure.
type UserBillingLimitInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserBillingLimitInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserBillingLimitInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUserBillingLimitInfoOK creates a UserBillingLimitInfoOK with default headers values
func NewUserBillingLimitInfoOK() *UserBillingLimitInfoOK {
	return &UserBillingLimitInfoOK{}
}

/*UserBillingLimitInfoOK handles this case with default header values.

successful operation
*/
type UserBillingLimitInfoOK struct {
	Payload *models.JSONResponseDataBillingLimit
}

func (o *UserBillingLimitInfoOK) Error() string {
	return fmt.Sprintf("[GET /user/billinglimit][%d] userBillingLimitInfoOK  %+v", 200, o.Payload)
}

func (o *UserBillingLimitInfoOK) GetPayload() *models.JSONResponseDataBillingLimit {
	return o.Payload
}

func (o *UserBillingLimitInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataBillingLimit)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
