// Code generated by go-swagger; DO NOT EDIT.

package user_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// UserCopyReader is a Reader for the UserCopy structure.
type UserCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserCopyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /user/{name}/{context}/copy] userCopy", response, response.Code())
	}
}

// NewUserCopyOK creates a UserCopyOK with default headers values
func NewUserCopyOK() *UserCopyOK {
	return &UserCopyOK{}
}

/*
UserCopyOK describes a response with status code 200, with default header values.

successful operation
*/
type UserCopyOK struct {
	Payload *models.JSONResponseDataBasicUser
}

// IsSuccess returns true when this user copy o k response has a 2xx status code
func (o *UserCopyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this user copy o k response has a 3xx status code
func (o *UserCopyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this user copy o k response has a 4xx status code
func (o *UserCopyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this user copy o k response has a 5xx status code
func (o *UserCopyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this user copy o k response a status code equal to that given
func (o *UserCopyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the user copy o k response
func (o *UserCopyOK) Code() int {
	return 200
}

func (o *UserCopyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /user/{name}/{context}/copy][%d] userCopyOK %s", 200, payload)
}

func (o *UserCopyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /user/{name}/{context}/copy][%d] userCopyOK %s", 200, payload)
}

func (o *UserCopyOK) GetPayload() *models.JSONResponseDataBasicUser {
	return o.Payload
}

func (o *UserCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataBasicUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
