// Code generated by go-swagger; DO NOT EDIT.

package user_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewUserProfileInfoParams creates a new UserProfileInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserProfileInfoParams() *UserProfileInfoParams {
	return &UserProfileInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserProfileInfoParamsWithTimeout creates a new UserProfileInfoParams object
// with the ability to set a timeout on a request.
func NewUserProfileInfoParamsWithTimeout(timeout time.Duration) *UserProfileInfoParams {
	return &UserProfileInfoParams{
		timeout: timeout,
	}
}

// NewUserProfileInfoParamsWithContext creates a new UserProfileInfoParams object
// with the ability to set a context for a request.
func NewUserProfileInfoParamsWithContext(ctx context.Context) *UserProfileInfoParams {
	return &UserProfileInfoParams{
		Context: ctx,
	}
}

// NewUserProfileInfoParamsWithHTTPClient creates a new UserProfileInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserProfileInfoParamsWithHTTPClient(client *http.Client) *UserProfileInfoParams {
	return &UserProfileInfoParams{
		HTTPClient: client,
	}
}

/*
UserProfileInfoParams contains all the parameters to send to the API endpoint

	for the user profile info operation.

	Typically these are written to a http.Request.
*/
type UserProfileInfoParams struct {

	// XDomainrobot2FAToken.
	//
	// Format: int32
	XDomainrobot2FAToken *int32

	// XDomainrobotBulkLimit.
	//
	// Format: int32
	XDomainrobotBulkLimit *int32

	// XDomainrobotContext.
	//
	// Format: int32
	XDomainrobotContext *int32

	// XDomainrobotDemo.
	XDomainrobotDemo *bool

	// XDomainrobotDomainSafePin.
	XDomainrobotDomainSafePin *string

	// XDomainrobotDomainSafeTan.
	XDomainrobotDomainSafeTan *string

	// XDomainrobotDomainSafeTransaction.
	XDomainrobotDomainSafeTransaction *string

	// XDomainrobotDomainSafeTransactionExpire.
	//
	// Format: date-time
	XDomainrobotDomainSafeTransactionExpire *strfmt.DateTime

	// XDomainrobotOwnerContext.
	//
	// Format: int32
	XDomainrobotOwnerContext *int32

	// XDomainrobotOwnerUser.
	XDomainrobotOwnerUser *string

	// XDomainrobotSessionID.
	XDomainrobotSessionID *string

	// XDomainrobotWS.
	XDomainrobotWS *string

	/* Body.

	   user
	*/
	Body *models.User

	// Context.
	//
	// Format: int32
	Context int32

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user profile info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserProfileInfoParams) WithDefaults() *UserProfileInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user profile info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserProfileInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user profile info params
func (o *UserProfileInfoParams) WithTimeout(timeout time.Duration) *UserProfileInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user profile info params
func (o *UserProfileInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user profile info params
func (o *UserProfileInfoParams) WithContext(ctx context.Context) *UserProfileInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user profile info params
func (o *UserProfileInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user profile info params
func (o *UserProfileInfoParams) WithHTTPClient(client *http.Client) *UserProfileInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user profile info params
func (o *UserProfileInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXDomainrobot2FAToken adds the xDomainrobot2FAToken to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobot2FAToken(xDomainrobot2FAToken *int32) *UserProfileInfoParams {
	o.SetXDomainrobot2FAToken(xDomainrobot2FAToken)
	return o
}

// SetXDomainrobot2FAToken adds the xDomainrobot2FAToken to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobot2FAToken(xDomainrobot2FAToken *int32) {
	o.XDomainrobot2FAToken = xDomainrobot2FAToken
}

// WithXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) *UserProfileInfoParams {
	o.SetXDomainrobotBulkLimit(xDomainrobotBulkLimit)
	return o
}

// SetXDomainrobotBulkLimit adds the xDomainrobotBulkLimit to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotBulkLimit(xDomainrobotBulkLimit *int32) {
	o.XDomainrobotBulkLimit = xDomainrobotBulkLimit
}

// WithXDomainrobotContext adds the xDomainrobotContext to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotContext(xDomainrobotContext *int32) *UserProfileInfoParams {
	o.SetXDomainrobotContext(xDomainrobotContext)
	return o
}

// SetXDomainrobotContext adds the xDomainrobotContext to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotContext(xDomainrobotContext *int32) {
	o.XDomainrobotContext = xDomainrobotContext
}

// WithXDomainrobotDemo adds the xDomainrobotDemo to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotDemo(xDomainrobotDemo *bool) *UserProfileInfoParams {
	o.SetXDomainrobotDemo(xDomainrobotDemo)
	return o
}

// SetXDomainrobotDemo adds the xDomainrobotDemo to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotDemo(xDomainrobotDemo *bool) {
	o.XDomainrobotDemo = xDomainrobotDemo
}

// WithXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) *UserProfileInfoParams {
	o.SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin)
	return o
}

// SetXDomainrobotDomainSafePin adds the xDomainrobotDomainSafePin to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotDomainSafePin(xDomainrobotDomainSafePin *string) {
	o.XDomainrobotDomainSafePin = xDomainrobotDomainSafePin
}

// WithXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) *UserProfileInfoParams {
	o.SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan)
	return o
}

// SetXDomainrobotDomainSafeTan adds the xDomainrobotDomainSafeTan to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotDomainSafeTan(xDomainrobotDomainSafeTan *string) {
	o.XDomainrobotDomainSafeTan = xDomainrobotDomainSafeTan
}

// WithXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) *UserProfileInfoParams {
	o.SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction)
	return o
}

// SetXDomainrobotDomainSafeTransaction adds the xDomainrobotDomainSafeTransaction to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotDomainSafeTransaction(xDomainrobotDomainSafeTransaction *string) {
	o.XDomainrobotDomainSafeTransaction = xDomainrobotDomainSafeTransaction
}

// WithXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) *UserProfileInfoParams {
	o.SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire)
	return o
}

// SetXDomainrobotDomainSafeTransactionExpire adds the xDomainrobotDomainSafeTransactionExpire to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotDomainSafeTransactionExpire(xDomainrobotDomainSafeTransactionExpire *strfmt.DateTime) {
	o.XDomainrobotDomainSafeTransactionExpire = xDomainrobotDomainSafeTransactionExpire
}

// WithXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) *UserProfileInfoParams {
	o.SetXDomainrobotOwnerContext(xDomainrobotOwnerContext)
	return o
}

// SetXDomainrobotOwnerContext adds the xDomainrobotOwnerContext to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotOwnerContext(xDomainrobotOwnerContext *int32) {
	o.XDomainrobotOwnerContext = xDomainrobotOwnerContext
}

// WithXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) *UserProfileInfoParams {
	o.SetXDomainrobotOwnerUser(xDomainrobotOwnerUser)
	return o
}

// SetXDomainrobotOwnerUser adds the xDomainrobotOwnerUser to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotOwnerUser(xDomainrobotOwnerUser *string) {
	o.XDomainrobotOwnerUser = xDomainrobotOwnerUser
}

// WithXDomainrobotSessionID adds the xDomainrobotSessionID to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotSessionID(xDomainrobotSessionID *string) *UserProfileInfoParams {
	o.SetXDomainrobotSessionID(xDomainrobotSessionID)
	return o
}

// SetXDomainrobotSessionID adds the xDomainrobotSessionId to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotSessionID(xDomainrobotSessionID *string) {
	o.XDomainrobotSessionID = xDomainrobotSessionID
}

// WithXDomainrobotWS adds the xDomainrobotWS to the user profile info params
func (o *UserProfileInfoParams) WithXDomainrobotWS(xDomainrobotWS *string) *UserProfileInfoParams {
	o.SetXDomainrobotWS(xDomainrobotWS)
	return o
}

// SetXDomainrobotWS adds the xDomainrobotWS to the user profile info params
func (o *UserProfileInfoParams) SetXDomainrobotWS(xDomainrobotWS *string) {
	o.XDomainrobotWS = xDomainrobotWS
}

// WithBody adds the body to the user profile info params
func (o *UserProfileInfoParams) WithBody(body *models.User) *UserProfileInfoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the user profile info params
func (o *UserProfileInfoParams) SetBody(body *models.User) {
	o.Body = body
}

// WithContext adds the context to the user profile info params
func (o *UserProfileInfoParams) WithContext(context int32) *UserProfileInfoParams {
	o.SetContext(context)
	return o
}

// SetContext adds the context to the user profile info params
func (o *UserProfileInfoParams) SetContext(context int32) {
	o.Context = context
}

// WithName adds the name to the user profile info params
func (o *UserProfileInfoParams) WithName(name string) *UserProfileInfoParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the user profile info params
func (o *UserProfileInfoParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UserProfileInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XDomainrobot2FAToken != nil {

		// header param X-Domainrobot-2FA-Token
		if err := r.SetHeaderParam("X-Domainrobot-2FA-Token", swag.FormatInt32(*o.XDomainrobot2FAToken)); err != nil {
			return err
		}
	}

	if o.XDomainrobotBulkLimit != nil {

		// header param X-Domainrobot-Bulk-Limit
		if err := r.SetHeaderParam("X-Domainrobot-Bulk-Limit", swag.FormatInt32(*o.XDomainrobotBulkLimit)); err != nil {
			return err
		}
	}

	if o.XDomainrobotContext != nil {

		// header param X-Domainrobot-Context
		if err := r.SetHeaderParam("X-Domainrobot-Context", swag.FormatInt32(*o.XDomainrobotContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDemo != nil {

		// header param X-Domainrobot-Demo
		if err := r.SetHeaderParam("X-Domainrobot-Demo", swag.FormatBool(*o.XDomainrobotDemo)); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafePin != nil {

		// header param X-Domainrobot-Domain-Safe-Pin
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Pin", *o.XDomainrobotDomainSafePin); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTan != nil {

		// header param X-Domainrobot-Domain-Safe-Tan
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Tan", *o.XDomainrobotDomainSafeTan); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransaction != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction", *o.XDomainrobotDomainSafeTransaction); err != nil {
			return err
		}
	}

	if o.XDomainrobotDomainSafeTransactionExpire != nil {

		// header param X-Domainrobot-Domain-Safe-Transaction-Expire
		if err := r.SetHeaderParam("X-Domainrobot-Domain-Safe-Transaction-Expire", o.XDomainrobotDomainSafeTransactionExpire.String()); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerContext != nil {

		// header param X-Domainrobot-Owner-Context
		if err := r.SetHeaderParam("X-Domainrobot-Owner-Context", swag.FormatInt32(*o.XDomainrobotOwnerContext)); err != nil {
			return err
		}
	}

	if o.XDomainrobotOwnerUser != nil {

		// header param X-Domainrobot-Owner-User
		if err := r.SetHeaderParam("X-Domainrobot-Owner-User", *o.XDomainrobotOwnerUser); err != nil {
			return err
		}
	}

	if o.XDomainrobotSessionID != nil {

		// header param X-Domainrobot-SessionId
		if err := r.SetHeaderParam("X-Domainrobot-SessionId", *o.XDomainrobotSessionID); err != nil {
			return err
		}
	}

	if o.XDomainrobotWS != nil {

		// header param X-Domainrobot-WS
		if err := r.SetHeaderParam("X-Domainrobot-WS", *o.XDomainrobotWS); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param context
	if err := r.SetPathParam("context", swag.FormatInt32(o.Context)); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
