// Code generated by go-swagger; DO NOT EDIT.

package mail_proxy_bulk_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// MailProxyCreatesReader is a Reader for the MailProxyCreates structure.
type MailProxyCreatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MailProxyCreatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMailProxyCreatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMailProxyCreatesOK creates a MailProxyCreatesOK with default headers values
func NewMailProxyCreatesOK() *MailProxyCreatesOK {
	return &MailProxyCreatesOK{}
}

/*MailProxyCreatesOK handles this case with default header values.

successful operation
*/
type MailProxyCreatesOK struct {
	Payload *models.JSONResponseDataListJSONResponseDataMailProxy
}

func (o *MailProxyCreatesOK) Error() string {
	return fmt.Sprintf("[POST /bulk/mailProxy][%d] mailProxyCreatesOK  %+v", 200, o.Payload)
}

func (o *MailProxyCreatesOK) GetPayload() *models.JSONResponseDataListJSONResponseDataMailProxy {
	return o.Payload
}

func (o *MailProxyCreatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataListJSONResponseDataMailProxy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
