// Code generated by go-swagger; DO NOT EDIT.

package customer_account_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// AccountInfoReader is a Reader for the AccountInfo structure.
type AccountInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /account] AccountInfo", response, response.Code())
	}
}

// NewAccountInfoOK creates a AccountInfoOK with default headers values
func NewAccountInfoOK() *AccountInfoOK {
	return &AccountInfoOK{}
}

/*
AccountInfoOK describes a response with status code 200, with default header values.

successful operation
*/
type AccountInfoOK struct {
	Payload *models.JSONResponseDataAccount
}

// IsSuccess returns true when this account info o k response has a 2xx status code
func (o *AccountInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account info o k response has a 3xx status code
func (o *AccountInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account info o k response has a 4xx status code
func (o *AccountInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this account info o k response has a 5xx status code
func (o *AccountInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this account info o k response a status code equal to that given
func (o *AccountInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the account info o k response
func (o *AccountInfoOK) Code() int {
	return 200
}

func (o *AccountInfoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account][%d] accountInfoOK %s", 200, payload)
}

func (o *AccountInfoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account][%d] accountInfoOK %s", 200, payload)
}

func (o *AccountInfoOK) GetPayload() *models.JSONResponseDataAccount {
	return o.Payload
}

func (o *AccountInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
