// Code generated by go-swagger; DO NOT EDIT.

package certificate_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// CertificateCreateReader is a Reader for the CertificateCreate structure.
type CertificateCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CertificateCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCertificateCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /certificate] certificateCreate", response, response.Code())
	}
}

// NewCertificateCreateOK creates a CertificateCreateOK with default headers values
func NewCertificateCreateOK() *CertificateCreateOK {
	return &CertificateCreateOK{}
}

/*
CertificateCreateOK describes a response with status code 200, with default header values.

successful operation
*/
type CertificateCreateOK struct {
	Payload *models.JSONResponseDataJob
}

// IsSuccess returns true when this certificate create o k response has a 2xx status code
func (o *CertificateCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this certificate create o k response has a 3xx status code
func (o *CertificateCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this certificate create o k response has a 4xx status code
func (o *CertificateCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this certificate create o k response has a 5xx status code
func (o *CertificateCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this certificate create o k response a status code equal to that given
func (o *CertificateCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the certificate create o k response
func (o *CertificateCreateOK) Code() int {
	return 200
}

func (o *CertificateCreateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /certificate][%d] certificateCreateOK %s", 200, payload)
}

func (o *CertificateCreateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /certificate][%d] certificateCreateOK %s", 200, payload)
}

func (o *CertificateCreateOK) GetPayload() *models.JSONResponseDataJob {
	return o.Payload
}

func (o *CertificateCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataJob)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
