// Code generated by go-swagger; DO NOT EDIT.

package backup_mx_bulk_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// BackupMxDeletesReader is a Reader for the BackupMxDeletes structure.
type BackupMxDeletesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BackupMxDeletesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBackupMxDeletesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBackupMxDeletesOK creates a BackupMxDeletesOK with default headers values
func NewBackupMxDeletesOK() *BackupMxDeletesOK {
	return &BackupMxDeletesOK{}
}

/*BackupMxDeletesOK handles this case with default header values.

successful operation
*/
type BackupMxDeletesOK struct {
	Payload *models.JSONResponseDataListJSONResponseDataBackupMx
}

func (o *BackupMxDeletesOK) Error() string {
	return fmt.Sprintf("[DELETE /bulk/backupMx][%d] backupMxDeletesOK  %+v", 200, o.Payload)
}

func (o *BackupMxDeletesOK) GetPayload() *models.JSONResponseDataListJSONResponseDataBackupMx {
	return o.Payload
}

func (o *BackupMxDeletesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONResponseDataListJSONResponseDataBackupMx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
