// Code generated by go-swagger; DO NOT EDIT.

package tmch_mark_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTmchMarkDocumentDeleteParams creates a new TmchMarkDocumentDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTmchMarkDocumentDeleteParams() *TmchMarkDocumentDeleteParams {
	return &TmchMarkDocumentDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTmchMarkDocumentDeleteParamsWithTimeout creates a new TmchMarkDocumentDeleteParams object
// with the ability to set a timeout on a request.
func NewTmchMarkDocumentDeleteParamsWithTimeout(timeout time.Duration) *TmchMarkDocumentDeleteParams {
	return &TmchMarkDocumentDeleteParams{
		timeout: timeout,
	}
}

// NewTmchMarkDocumentDeleteParamsWithContext creates a new TmchMarkDocumentDeleteParams object
// with the ability to set a context for a request.
func NewTmchMarkDocumentDeleteParamsWithContext(ctx context.Context) *TmchMarkDocumentDeleteParams {
	return &TmchMarkDocumentDeleteParams{
		Context: ctx,
	}
}

// NewTmchMarkDocumentDeleteParamsWithHTTPClient creates a new TmchMarkDocumentDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewTmchMarkDocumentDeleteParamsWithHTTPClient(client *http.Client) *TmchMarkDocumentDeleteParams {
	return &TmchMarkDocumentDeleteParams{
		HTTPClient: client,
	}
}

/*
TmchMarkDocumentDeleteParams contains all the parameters to send to the API endpoint

	for the tmch mark document delete operation.

	Typically these are written to a http.Request.
*/
type TmchMarkDocumentDeleteParams struct {

	// Reference.
	Reference string

	// Type.
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tmch mark document delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TmchMarkDocumentDeleteParams) WithDefaults() *TmchMarkDocumentDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tmch mark document delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TmchMarkDocumentDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) WithTimeout(timeout time.Duration) *TmchMarkDocumentDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) WithContext(ctx context.Context) *TmchMarkDocumentDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) WithHTTPClient(client *http.Client) *TmchMarkDocumentDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReference adds the reference to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) WithReference(reference string) *TmchMarkDocumentDeleteParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) SetReference(reference string) {
	o.Reference = reference
}

// WithType adds the typeVar to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) WithType(typeVar string) *TmchMarkDocumentDeleteParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the tmch mark document delete params
func (o *TmchMarkDocumentDeleteParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *TmchMarkDocumentDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
