// Code generated by go-swagger; DO NOT EDIT.

package tmch_mark_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hostwithquantum/internetx-autodns-go/models"
)

// NewTmchMarkImportParams creates a new TmchMarkImportParams object
// with the default values initialized.
func NewTmchMarkImportParams() *TmchMarkImportParams {
	var ()
	return &TmchMarkImportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTmchMarkImportParamsWithTimeout creates a new TmchMarkImportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTmchMarkImportParamsWithTimeout(timeout time.Duration) *TmchMarkImportParams {
	var ()
	return &TmchMarkImportParams{

		timeout: timeout,
	}
}

// NewTmchMarkImportParamsWithContext creates a new TmchMarkImportParams object
// with the default values initialized, and the ability to set a context for a request
func NewTmchMarkImportParamsWithContext(ctx context.Context) *TmchMarkImportParams {
	var ()
	return &TmchMarkImportParams{

		Context: ctx,
	}
}

// NewTmchMarkImportParamsWithHTTPClient creates a new TmchMarkImportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTmchMarkImportParamsWithHTTPClient(client *http.Client) *TmchMarkImportParams {
	var ()
	return &TmchMarkImportParams{
		HTTPClient: client,
	}
}

/*TmchMarkImportParams contains all the parameters to send to the API endpoint
for the tmch mark import operation typically these are written to a http.Request
*/
type TmchMarkImportParams struct {

	/*Body
	  tmchMark

	*/
	Body *models.TmchMark

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tmch mark import params
func (o *TmchMarkImportParams) WithTimeout(timeout time.Duration) *TmchMarkImportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tmch mark import params
func (o *TmchMarkImportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tmch mark import params
func (o *TmchMarkImportParams) WithContext(ctx context.Context) *TmchMarkImportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tmch mark import params
func (o *TmchMarkImportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tmch mark import params
func (o *TmchMarkImportParams) WithHTTPClient(client *http.Client) *TmchMarkImportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tmch mark import params
func (o *TmchMarkImportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the tmch mark import params
func (o *TmchMarkImportParams) WithBody(body *models.TmchMark) *TmchMarkImportParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the tmch mark import params
func (o *TmchMarkImportParams) SetBody(body *models.TmchMark) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TmchMarkImportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
