// Code generated by go-swagger; DO NOT EDIT.

package tmch_mark_claim_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewClaimRejectParams creates a new ClaimRejectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClaimRejectParams() *ClaimRejectParams {
	return &ClaimRejectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClaimRejectParamsWithTimeout creates a new ClaimRejectParams object
// with the ability to set a timeout on a request.
func NewClaimRejectParamsWithTimeout(timeout time.Duration) *ClaimRejectParams {
	return &ClaimRejectParams{
		timeout: timeout,
	}
}

// NewClaimRejectParamsWithContext creates a new ClaimRejectParams object
// with the ability to set a context for a request.
func NewClaimRejectParamsWithContext(ctx context.Context) *ClaimRejectParams {
	return &ClaimRejectParams{
		Context: ctx,
	}
}

// NewClaimRejectParamsWithHTTPClient creates a new ClaimRejectParams object
// with the ability to set a custom HTTPClient for a request.
func NewClaimRejectParamsWithHTTPClient(client *http.Client) *ClaimRejectParams {
	return &ClaimRejectParams{
		HTTPClient: client,
	}
}

/*
ClaimRejectParams contains all the parameters to send to the API endpoint

	for the claim reject operation.

	Typically these are written to a http.Request.
*/
type ClaimRejectParams struct {

	// Reference.
	Reference string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the claim reject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClaimRejectParams) WithDefaults() *ClaimRejectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the claim reject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClaimRejectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the claim reject params
func (o *ClaimRejectParams) WithTimeout(timeout time.Duration) *ClaimRejectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the claim reject params
func (o *ClaimRejectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the claim reject params
func (o *ClaimRejectParams) WithContext(ctx context.Context) *ClaimRejectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the claim reject params
func (o *ClaimRejectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the claim reject params
func (o *ClaimRejectParams) WithHTTPClient(client *http.Client) *ClaimRejectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the claim reject params
func (o *ClaimRejectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReference adds the reference to the claim reject params
func (o *ClaimRejectParams) WithReference(reference string) *ClaimRejectParams {
	o.SetReference(reference)
	return o
}

// SetReference adds the reference to the claim reject params
func (o *ClaimRejectParams) SetReference(reference string) {
	o.Reference = reference
}

// WriteToRequest writes these params to a swagger request
func (o *ClaimRejectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param reference
	if err := r.SetPathParam("reference", o.Reference); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
