// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainCancelationExtensions domain cancelation extensions
//
// swagger:model DomainCancelationExtensions
type DomainCancelationExtensions struct {

	// The cancelation date
	// Format: date-time
	Cancelation strfmt.DateTime `json:"cancelation,omitempty"`

	// The disconnected
	Disconnected bool `json:"disconnected,omitempty"`
}

// Validate validates this domain cancelation extensions
func (m *DomainCancelationExtensions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCancelation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainCancelationExtensions) validateCancelation(formats strfmt.Registry) error {
	if swag.IsZero(m.Cancelation) { // not required
		return nil
	}

	if err := validate.FormatOf("cancelation", "body", "date-time", m.Cancelation.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this domain cancelation extensions based on context it is used
func (m *DomainCancelationExtensions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DomainCancelationExtensions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainCancelationExtensions) UnmarshalBinary(b []byte) error {
	var res DomainCancelationExtensions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
