// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainMonitoring domain monitoring
//
// swagger:model DomainMonitoring
type DomainMonitoring struct {

	// Monitoring setting for domain cancelations.
	// false = Domain cancelations should not be monitored.
	// true = Domain cancelations should be monitored.
	// Default value = false
	Cancelation bool `json:"cancelation,omitempty"`

	// Date of creation.
	// Format: date-time
	Created strfmt.DateTime `json:"created,omitempty"`

	// The IDN version of the domain written in Punycode syntax to be monitored.
	Idn string `json:"idn,omitempty"`

	// Contains the setup data for domain monitoring.
	MonitoringSetups []*DomainMonitoringSetup `json:"monitoringSetups"`

	// Domain to be monitored.
	// Example: domain.de
	Name string `json:"name,omitempty"`

	// Email addresses to which an email is sent when the status changes.
	NotificationEmails []string `json:"notificationEmails"`

	// Mobile phone number to which an SMS is sent when the status changes.
	NotificationMobiles []Phone `json:"notificationMobiles"`

	// Monitoring setting for OwnerC validation.
	// false = OwnerC validation should not be monitored.
	// true = OwnerC validation should be monitored.
	// Default value = false
	Ocval bool `json:"ocval,omitempty"`

	// The object owner.
	Owner *BasicUser `json:"owner,omitempty"`

	// Monitoring setting for domain deletions.
	// false = Domain deletions should not be monitored.
	// true = Domain deletions should be monitored.
	// Default value = false
	Removed bool `json:"removed,omitempty"`

	// Date of the last update.
	// Format: date-time
	Updated strfmt.DateTime `json:"updated,omitempty"`

	// User who performed the last update.
	Updater *BasicUser `json:"updater,omitempty"`
}

// Validate validates this domain monitoring
func (m *DomainMonitoring) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMonitoringSetups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdater(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainMonitoring) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *DomainMonitoring) validateMonitoringSetups(formats strfmt.Registry) error {
	if swag.IsZero(m.MonitoringSetups) { // not required
		return nil
	}

	for i := 0; i < len(m.MonitoringSetups); i++ {
		if swag.IsZero(m.MonitoringSetups[i]) { // not required
			continue
		}

		if m.MonitoringSetups[i] != nil {
			if err := m.MonitoringSetups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("monitoringSetups" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("monitoringSetups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DomainMonitoring) validateOwner(formats strfmt.Registry) error {
	if swag.IsZero(m.Owner) { // not required
		return nil
	}

	if m.Owner != nil {
		if err := m.Owner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("owner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("owner")
			}
			return err
		}
	}

	return nil
}

func (m *DomainMonitoring) validateUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if err := validate.FormatOf("updated", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *DomainMonitoring) validateUpdater(formats strfmt.Registry) error {
	if swag.IsZero(m.Updater) { // not required
		return nil
	}

	if m.Updater != nil {
		if err := m.Updater.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updater")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updater")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this domain monitoring based on the context it is used
func (m *DomainMonitoring) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMonitoringSetups(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOwner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdater(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainMonitoring) contextValidateMonitoringSetups(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MonitoringSetups); i++ {

		if m.MonitoringSetups[i] != nil {

			if swag.IsZero(m.MonitoringSetups[i]) { // not required
				return nil
			}

			if err := m.MonitoringSetups[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("monitoringSetups" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("monitoringSetups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DomainMonitoring) contextValidateOwner(ctx context.Context, formats strfmt.Registry) error {

	if m.Owner != nil {

		if swag.IsZero(m.Owner) { // not required
			return nil
		}

		if err := m.Owner.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("owner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("owner")
			}
			return err
		}
	}

	return nil
}

func (m *DomainMonitoring) contextValidateUpdater(ctx context.Context, formats strfmt.Registry) error {

	if m.Updater != nil {

		if swag.IsZero(m.Updater) { // not required
			return nil
		}

		if err := m.Updater.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updater")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updater")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DomainMonitoring) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainMonitoring) UnmarshalBinary(b []byte) error {
	var res DomainMonitoring
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
