// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExtendedValidationExtension extended validation extension
//
// swagger:model ExtendedValidationExtension
type ExtendedValidationExtension struct {

	// Additional validation data required for certain Comodo products.
	BusinessCategory BusinessCategory `json:"businessCategory,omitempty"`

	// The company number
	CompanyNumber string `json:"companyNumber,omitempty"`

	// Country of judicial formation
	JoiCountryName string `json:"joiCountryName,omitempty"`
}

// Validate validates this extended validation extension
func (m *ExtendedValidationExtension) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBusinessCategory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtendedValidationExtension) validateBusinessCategory(formats strfmt.Registry) error {

	if swag.IsZero(m.BusinessCategory) { // not required
		return nil
	}

	if err := m.BusinessCategory.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("businessCategory")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExtendedValidationExtension) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtendedValidationExtension) UnmarshalBinary(b []byte) error {
	var res ExtendedValidationExtension
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
