// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// RenewStatusConstants renew status constants
//
// swagger:model RenewStatusConstants
type RenewStatusConstants string

const (

	// RenewStatusConstantsAUTO captures enum value "AUTO"
	RenewStatusConstantsAUTO RenewStatusConstants = "AUTO"

	// RenewStatusConstantsCANCELED captures enum value "CANCELED"
	RenewStatusConstantsCANCELED RenewStatusConstants = "CANCELED"

	// RenewStatusConstantsONCE captures enum value "ONCE"
	RenewStatusConstantsONCE RenewStatusConstants = "ONCE"
)

// for schema
var renewStatusConstantsEnum []interface{}

func init() {
	var res []RenewStatusConstants
	if err := json.Unmarshal([]byte(`["AUTO","CANCELED","ONCE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		renewStatusConstantsEnum = append(renewStatusConstantsEnum, v)
	}
}

func (m RenewStatusConstants) validateRenewStatusConstantsEnum(path, location string, value RenewStatusConstants) error {
	if err := validate.EnumCase(path, location, value, renewStatusConstantsEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this renew status constants
func (m RenewStatusConstants) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRenewStatusConstantsEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
