// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SiteSealInformation site seal information
//
// swagger:model SiteSealInformation
type SiteSealInformation struct {

	// The hash value for the site seal.
	Hash string `json:"hash,omitempty"`

	// The plain html markup.
	HTML string `json:"html,omitempty"`

	// The icon url.
	Icon string `json:"icon,omitempty"`

	// The preview url.
	Preview string `json:"preview,omitempty"`

	// The size of the site seal.
	Size string `json:"size,omitempty"`
}

// Validate validates this site seal information
func (m *SiteSealInformation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this site seal information based on context it is used
func (m *SiteSealInformation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SiteSealInformation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SiteSealInformation) UnmarshalBinary(b []byte) error {
	var res SiteSealInformation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
