// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TrustedApplicationFunctions trusted application functions
//
// swagger:model TrustedApplicationFunctions
type TrustedApplicationFunctions struct {

	// The allowed functions for the trusted application.
	// Unique: true
	FunctionCodes []string `json:"functionCodes"`
}

// Validate validates this trusted application functions
func (m *TrustedApplicationFunctions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFunctionCodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TrustedApplicationFunctions) validateFunctionCodes(formats strfmt.Registry) error {
	if swag.IsZero(m.FunctionCodes) { // not required
		return nil
	}

	if err := validate.UniqueItems("functionCodes", "body", m.FunctionCodes); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this trusted application functions based on context it is used
func (m *TrustedApplicationFunctions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrustedApplicationFunctions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrustedApplicationFunctions) UnmarshalBinary(b []byte) error {
	var res TrustedApplicationFunctions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
