// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VmcCheckData vmc check data
//
// swagger:model VmcCheckData
type VmcCheckData struct {

	// The common name.
	Name string `json:"name,omitempty"`

	// The ssl product.
	Product string `json:"product,omitempty"`

	// The subject alternative names, listed in the csr.
	SubjectAlternativeNames []*SubjectAlternativeName `json:"subjectAlternativeNames"`

	// The base64 encoded SVG logo
	VmcLogo string `json:"vmcLogo,omitempty"`
}

// Validate validates this vmc check data
func (m *VmcCheckData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubjectAlternativeNames(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VmcCheckData) validateSubjectAlternativeNames(formats strfmt.Registry) error {
	if swag.IsZero(m.SubjectAlternativeNames) { // not required
		return nil
	}

	for i := 0; i < len(m.SubjectAlternativeNames); i++ {
		if swag.IsZero(m.SubjectAlternativeNames[i]) { // not required
			continue
		}

		if m.SubjectAlternativeNames[i] != nil {
			if err := m.SubjectAlternativeNames[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("subjectAlternativeNames" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("subjectAlternativeNames" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this vmc check data based on the context it is used
func (m *VmcCheckData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubjectAlternativeNames(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VmcCheckData) contextValidateSubjectAlternativeNames(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SubjectAlternativeNames); i++ {

		if m.SubjectAlternativeNames[i] != nil {

			if swag.IsZero(m.SubjectAlternativeNames[i]) { // not required
				return nil
			}

			if err := m.SubjectAlternativeNames[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("subjectAlternativeNames" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("subjectAlternativeNames" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VmcCheckData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmcCheckData) UnmarshalBinary(b []byte) error {
	var res VmcCheckData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
